version: 1.2
workflows:
   - name: "rz_test_star_solo"
     subclass: WDL
     primaryDescriptorPath: /combinomics.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
         tags:
             - /.*/

   - name: "Combinomics-peak-to-gene"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-find-dorcs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
         tags:
             - /.*/

   - name: "Combinomics-archr"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-atac-archr.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
         tags:
             - /.*/

   - name: "Combinomics-seurat"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-rna-seurat.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
         tags:
             - /.*/

   - name: "Combinomics-sample-demultiplexing"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-preprocess.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
         tags:
             - /.*/

   - name: "Combinomics-merge-data"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-merge-data.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
         tags:
             - /.*/
